version: "3.8"
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis config file to use and add password
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports:
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project
    volumes:
      - $PWD/redis.conf:/usr/etc/redis/redis.conf
  go:
    container_name: "api"
    # build the image using docker file
    build:
      context: .
    ports:
      - "8080:8080"
